manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: englmaxi
      url-base: https://github.com/englmaxi
    - name: infely
      url-base: https://github.com/infely
    - name: ssonparote
      url-base: https://github.com/ssonparote
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-display
      remote: englmaxi
      revision: main
    - name: nice-view-battery
      remote: infely
      revision: main
    - name: zmk-sofle-rgb
      remote: ssonparote
      revision: main
  self:
    path: config
